/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import Auth.Login;
import javax.swing.Timer;
import java.awt.Color;
import java.awt.Image;
import java.awt.Toolkit;
import java.awt.event.ActionListener;
import java.awt.event.ActionEvent;
import javax.swing.JOptionPane;

/**
 *
 * @author ASUS
 */
public class Utama extends javax.swing.JFrame {

    /**
     * Creates new form Utama
     */
    public void Ubah_Warna() {
        Timer timer = new Timer(1000, new ActionListener() {
            private int count = 0; // Hitungan untuk mengubah warna
    
            @Override
            public void actionPerformed(ActionEvent e) {
                if (count % 2 == 0) {
                    jLabel2.setForeground(Color.RED); // Mengubah warna teks menjadi merah
                } else {
                    jLabel2.setForeground(Color.BLUE); // Mengubah warna teks menjadi biru
                }
                count++;
            }
        });
        
        timer.start(); // Memulai Timer untuk mengubah warna
    }
    
    public Utama() {
        initComponents();
        Ubah_Warna();
        setExtendedState(Utama.MAXIMIZED_BOTH);
        Image icon = Toolkit.getDefaultToolkit().getImage("src/Image/logo_kc.png");
        setIconImage(icon);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane2 = new javax.swing.JDesktopPane();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu3 = new javax.swing.JMenu();
        mn_User = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        mn_Tiket = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        mn_transportasi = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem5 = new javax.swing.JMenuItem();
        mn_Exit = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Home\n");

        jDesktopPane2.setBackground(new java.awt.Color(255, 153, 0));

        jLabel2.setFont(new java.awt.Font("STCaiyun", 1, 36)); // NOI18N
        jLabel2.setText("Si-TravelKu");

        jLabel3.setFont(new java.awt.Font("Segoe UI Emoji", 1, 14)); // NOI18N
        jLabel3.setText("Program Pemesanan Tiket Travel By Kelompok 2");

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/logo_utama-removebg-preview.png"))); // NOI18N

        jDesktopPane2.setLayer(jLabel2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane2.setLayer(jLabel3, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane2.setLayer(jLabel4, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDesktopPane2Layout = new javax.swing.GroupLayout(jDesktopPane2);
        jDesktopPane2.setLayout(jDesktopPane2Layout);
        jDesktopPane2Layout.setHorizontalGroup(
            jDesktopPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDesktopPane2Layout.createSequentialGroup()
                .addContainerGap(997, Short.MAX_VALUE)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 382, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jDesktopPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2))
                .addGap(59, 59, 59))
        );
        jDesktopPane2Layout.setVerticalGroup(
            jDesktopPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane2Layout.createSequentialGroup()
                .addGroup(jDesktopPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jDesktopPane2Layout.createSequentialGroup()
                        .addGap(329, 329, 329)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3))
                    .addGroup(jDesktopPane2Layout.createSequentialGroup()
                        .addGap(183, 183, 183)
                        .addComponent(jLabel4)))
                .addContainerGap(697, Short.MAX_VALUE))
        );

        jMenu3.setText("Master");

        mn_User.setText("Petugas");
        mn_User.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mn_UserActionPerformed(evt);
            }
        });
        jMenu3.add(mn_User);

        jMenuItem1.setText("Penumpang");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem1);

        mn_Tiket.setText("Tiket");
        mn_Tiket.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mn_TiketActionPerformed(evt);
            }
        });
        jMenu3.add(mn_Tiket);

        jMenuItem2.setText("Supir");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem2);

        mn_transportasi.setText("Kendaraan");
        mn_transportasi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mn_transportasiActionPerformed(evt);
            }
        });
        jMenu3.add(mn_transportasi);

        jMenuBar2.add(jMenu3);

        jMenu1.setText("Transaksi");

        jMenuItem3.setText("Pemesanan");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem3);

        jMenuBar2.add(jMenu1);

        jMenu5.setText("Report");

        jMenuItem4.setText("Histori Transaksi");
        jMenu5.add(jMenuItem4);

        jMenuBar2.add(jMenu5);

        jMenu2.setText("File");

        jMenuItem5.setText("Info");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem5);

        mn_Exit.setText("Exit");
        mn_Exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mn_ExitActionPerformed(evt);
            }
        });
        jMenu2.add(mn_Exit);

        jMenuBar2.add(jMenu2);

        setJMenuBar(jMenuBar2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane2)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jDesktopPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mn_ExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mn_ExitActionPerformed
        int opsi = JOptionPane.showConfirmDialog(null, "Apakah anda yakin untuk keluar?", "Logout", JOptionPane.YES_NO_OPTION);
        if(opsi == JOptionPane.YES_OPTION){
            Auth.Login login = new Login();
            login.setVisible(true);
            dispose();
            JOptionPane.showMessageDialog(null, "Anda berhasil keluar");
        } else {
        
        }    
    }//GEN-LAST:event_mn_ExitActionPerformed

    private void mn_UserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mn_UserActionPerformed
        DataPetugas user = new DataPetugas();
        user.setLocationRelativeTo(this);
        user.setVisible(true);
    }//GEN-LAST:event_mn_UserActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        DataPenumpang penumpang = new DataPenumpang();
        penumpang.setLocationRelativeTo(this);
        penumpang.setVisible(true);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void mn_TiketActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mn_TiketActionPerformed
        DataTiket tiket = new DataTiket();
        tiket.setLocationRelativeTo(this);
        tiket.setVisible(true);
    }//GEN-LAST:event_mn_TiketActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        DataInfo info = new DataInfo();
        info.setLocationRelativeTo(this);
        info.setVisible(true);
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        DataTransaksi transaksi = new DataTransaksi();
        transaksi.setLocationRelativeTo(this);
        transaksi.setVisible(true);

//        TransaksiData transaksi = new TransaksiData();
//        transaksi.setLocationRelativeTo(this);
//        transaksi.setVisible(true);
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void mn_transportasiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mn_transportasiActionPerformed
        DataKendaraan kendaraan = new DataKendaraan();
        kendaraan.setLocationRelativeTo(this);
        kendaraan.setVisible(true);
    }//GEN-LAST:event_mn_transportasiActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        DataSupir supir = new DataSupir();
        supir.setLocationRelativeTo(this);
        supir.setVisible(true);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Utama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Utama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Utama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Utama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Utama().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane jDesktopPane2;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem mn_Exit;
    private javax.swing.JMenuItem mn_Tiket;
    private javax.swing.JMenuItem mn_User;
    private javax.swing.JMenuItem mn_transportasi;
    // End of variables declaration//GEN-END:variables
}
